# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distactl < Formula
  desc "A CLI tool for Dista platform"
  homepage "https://github.com/distacartinc/distactl"
  version "0.9.7"
  license "MIT"

  depends_on "ghostscript"
  depends_on "poppler"

  on_macos do
    url "https://github.com/distacartinc/distactl-public/releases/download/v0.9.7/distactl-Darwin-all.tar.gz"
    sha256 "84286e4ef596e421f4be21c2e66284437ddab3596d6e8690c37f49a4dc31cb19"

    def install
      bin.install "distactl"
      # Install bash completions
      bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
      # Install zsh completions
      zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
      # Install fish completions
      fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
      # Install man pages
      man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v0.9.7/distactl-Linux-x86_64.tar.gz"
        sha256 "511f7786492b66be7423e6830689ec4ef52c9845f1822f83cfa2b6ef7a8f0735"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v0.9.7/distactl-Linux-armv6.tar.gz"
        sha256 "9d8eecd40c05cf38b55302430c289a0807aeb393e4255067c263190c0dd0ab6f"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v0.9.7/distactl-Linux-arm64.tar.gz"
        sha256 "09ea1b7367fa9083f025d89e17a28175d9bcb2675cbf017988ed15bbdca2e9bc"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
  end

  test do
    system "#{bin}/distactl --version"
  end
end
