# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distactl < Formula
  desc "A CLI tool for Dista platform"
  homepage "https://github.com/distacartinc/distactl"
  version "1.6.7"
  license "MIT"

  depends_on "ghostscript"
  depends_on "poppler"
  depends_on "tesseract"

  on_macos do
    url "https://github.com/distacartinc/distactl-public/releases/download/v1.6.7/distactl-Darwin-all.tar.gz"
    sha256 "2fd2bb2654b3936341b8c5e0b20c6eb846350a96e11b5685d29ecbe640ae4863"

    def install
      bin.install "distactl"
      # Install bash completions
      bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
      # Install zsh completions
      zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
      # Install fish completions
      fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
      # Install man pages
      man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v1.6.7/distactl-Linux-x86_64.tar.gz"
        sha256 "ddcfe873716bfeed79028b769a921af48dbb7f9270a3e5852e99523c08c06460"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v1.6.7/distactl-Linux-armv6.tar.gz"
        sha256 "e09aeca5e368d2386cf6d6cfca6c27cc3470c5c0967e9cd927100895e7075b2e"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v1.6.7/distactl-Linux-arm64.tar.gz"
        sha256 "0b723ea744ac97b0697fef2dfce71cb9a3e561461411257a79d78364b246c16f"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
  end

  test do
    system "#{bin}/distactl --version"
  end
end
