# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distactl < Formula
  desc "A CLI tool for Dista platform"
  homepage "https://github.com/distacartinc/distactl"
  version "1.1.1"
  license "MIT"

  depends_on "ghostscript"
  depends_on "poppler"
  depends_on "tesseract"

  on_macos do
    url "https://github.com/distacartinc/distactl-public/releases/download/v1.1.1/distactl-Darwin-all.tar.gz"
    sha256 "e3d4a94998899a7debca08c25161d59dca14bca8b886866f5ec9912477d929b2"

    def install
      bin.install "distactl"
      # Install bash completions
      bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
      # Install zsh completions
      zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
      # Install fish completions
      fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
      # Install man pages
      man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v1.1.1/distactl-Linux-x86_64.tar.gz"
        sha256 "f9588c6fe7b0d0879619697406e3e8642020b53b50038e2b9f57856d39fde858"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v1.1.1/distactl-Linux-armv6.tar.gz"
        sha256 "0d88c57598a4e6d2a2e94cf4ffda4bbc384dc3182d9d07d63f82c82b02d0fa23"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/distacartinc/distactl-public/releases/download/v1.1.1/distactl-Linux-arm64.tar.gz"
        sha256 "d1ee0941504b2addd894fb9b5120ce0d6226403d26de7de92eb0562713443ee5"

        def install
          bin.install "distactl"
          # Install bash completions
          bash_completion.install "assets/completions/distactl.bash" if File.exist?("assets/completions/distactl.bash")
          # Install zsh completions
          zsh_completion.install "assets/completions/_distactl" if File.exist?("assets/completions/_distactl")
          # Install fish completions
          fish_completion.install "assets/completions/distactl.fish" if File.exist?("assets/completions/distactl.fish")
          # Install man pages
          man1.install Dir["assets/manpages/*.1"] if Dir.exist?("assets/manpages")
        end
      end
    end
  end

  test do
    system "#{bin}/distactl --version"
  end
end
